name: MobCapturer
version: ${project.version}
author: TheBusyBiscuit
description: A Slimefun Addon that adds a tool that allows you to capture mobs
website: https://github.com/TheBusyBiscuit/MobCapturer

main: io.github.thebusybiscuit.mobcapturer.MobCapturer
depend: [Slimefun]

api-version: 1.14