name: Bug Report
description: Report bugs or problems about MobCapturer
labels: ["bug"]
assignees:
  - ybw0014
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to MobCapturer Bug Tracker
        Please take a look at [How to report bugs](https://github.com/Slimefun/Slimefun4/wiki/How-to-report-bugs) and [existing Issues](https://github.com/Slimefun-Addon-Community/MobCapturer/issues).

        <strong><i>Fields marked with an asterisk (*) are required.</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go through this checklist before you create the issue.
      options:
        - label: You are using official version downloaded from Builds (https://thebusybiscuit.github.io/builds/)
          required: true
        - label: You did not modify the jar file
          required: true
        - label: You searched existing issues, and could not find any existing bug report on this
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide detailed and clear description of what goes wrong.
        The more information you can provide, the easier we can handle this problem.
      placeholder: Only "doesn't work" won't help.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Tell us the exact steps to reproduce this issue, the more detailed the easier we can reproduce it.
        If you can provide a video reproduction, please paste your video link.
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        What were you expecting to happen?
        What do you think would have been the correct behaviour?
        Sometimes, you misunderstand an intended feature.
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Server log
      description: |
        Take a look at your server log and upload any full error message from Slimefun to pasting service [https://pastebin.com/](https://pastebin.com/)
        **DO NOT paste logs here**
      placeholder: https://pastebin.com/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: Error report
      description: |
        If the error generates a report at `/plugins/Slimefun/error-reports`, please upload to pasting service [https://pastebin.com/](https://pastebin.com/)
        **DO NOT paste error reports here**
      placeholder: https://pastebin.com/....
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: Server Software
      description: Please select the software your server is running on
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Other (Please specify in description)
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: Please select your Minecraft Version
      options:
        - 1.20.x
        - 1.19.x
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - Older versions are not supported
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Slimefun version
      description: |
        "latest" is not a valid version number, we need exact one.
        We recommend to run `/sf versions` and upload the screenshot, make sure the entire output is included.
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Plugin version
      description: |
        Please specify the plugin version (like `DEV - 1 (git XXXXXX)`)
    validations:
      required: true
