blank_issues_enabled: false
contact_links:
  - name: Slimefun Addon Community Discord Server
    url: https://discord.gg/SqD3gg5SAU
    about: Discuss bugs or ask for help in our Discord server! (DO NOT report bugs there)
